# Generated by Django 4.2.5 on 2023-09-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsession', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmodel',
            name='report_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
