# Generated by Django 4.2.5 on 2023-10-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsession', '0002_sessionmodel_report_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='session_name',
            field=models.CharField(max_length=32),
        ),
    ]
