# Generated by Django 4.2.5 on 2023-09-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsession', '0001_initial'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rn', models.PositiveBigIntegerField()),
                ('student_name', models.CharField(max_length=32)),
                ('branch_name', models.CharField(max_length=10)),
                ('section_name', models.CharField(max_length=10)),
                ('room_number', models.CharField(max_length=10)),
                ('marked', models.BooleanField(default=False)),
                ('report_link', models.CharField(blank=True, max_length=255, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='adminsession.sessionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='auth_app.adminmodel')),
            ],
            options={
                'db_table': 'seatingPlan',
            },
        ),
        migrations.CreateModel(
            name='RoomSeatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_rows', models.PositiveIntegerField()),
                ('room_columns', models.PositiveIntegerField()),
                ('room_breakout', models.CharField(max_length=32)),
                ('marked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='auth_app.adminmodel')),
            ],
            options={
                'db_table': 'roomSeatingPlan',
            },
        ),
    ]
