# Generated by Django 4.2.5 on 2023-09-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0003_alter_roomseatingmodel_seating_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatingplanmodel',
            name='report_link',
        ),
    ]
