# Generated by Django 4.2.5 on 2023-09-26 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collageInfo', '0006_roommodel_created_on'),
        ('seatingplan', '0004_remove_seatingplanmodel_report_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingplanmodel',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='collageInfo.branchmodel'),
        ),
        migrations.AddField(
            model_name='seatingplanmodel',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to='collageInfo.sectionmodel'),
        ),
    ]
