# Generated by Django 4.2.5 on 2023-09-29 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collageInfo', '0007_roommodel_room_remark_roommodel_room_type'),
        ('seatingplan', '0005_seatingplanmodel_branch_seatingplanmodel_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomseatingmodel',
            name='room_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomseatingmodel',
            name='room_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomseatingmodel',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='collageInfo.sectionmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seatingplanmodel',
            name='room_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
