# Generated by Django 4.2.5 on 2023-09-29 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminsession', '0002_sessionmodel_report_link'),
        ('seatingplan', '0006_roomseatingmodel_room_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomseatingmodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='adminsession.sessionmodel'),
        ),
    ]
