# Generated by Django 4.2.5 on 2023-09-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0008_remove_seatingplanmodel_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomseatingmodel',
            name='room_remark',
            field=models.IntegerField(default=0),
        ),
    ]
