# Generated by Django 4.2.5 on 2023-10-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0009_alter_roomseatingmodel_room_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomseatingmodel',
            name='room_breakout',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='roomseatingmodel',
            name='room_number',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='roomseatingmodel',
            name='room_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='seatingplanmodel',
            name='branch_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='seatingplanmodel',
            name='section_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='seatingplanmodel',
            name='student_name',
            field=models.CharField(max_length=128),
        ),
    ]
