# Generated by Django 4.2.5 on 2023-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatingplan', '0010_alter_roomseatingmodel_room_breakout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatingplanmodel',
            name='isDetained',
            field=models.BooleanField(default=False),
        ),
    ]
