# Generated by Django 4.2.5 on 2023-09-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collageInfo', '0006_roommodel_created_on'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='collageInfo.branchmodel'),
            preserve_default=False,
        ),
    ]
