# Generated by Django 4.2.5 on 2023-09-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageInfo', '0002_alter_branchmodel_branch_name_alter_branchmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommodel',
            name='room_breakout',
            field=models.CharField(max_length=32),
        ),
    ]
