# Generated by Django 4.2.5 on 2023-09-17 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collageInfo', '0005_roommodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
