# Generated by Django 4.2.5 on 2023-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageInfo', '0006_roommodel_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='room_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='room_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
